//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailbirdTest {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class MailBird : global::System.Configuration.ApplicationSettingsBase {
        
        private static MailBird defaultInstance = ((MailBird)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MailBird())));
        
        public static MailBird Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[{\r\n\"provider\":\"Gmail\",\r\n\"url\":\"mail.google.com\"\r\n},\r\n{\r\n\"provider\":\"Yahoo\",\r\n\"ur" +
            "l\":\"mail.google.com\"\r\n},\r\n{\r\n\"provider\":MSN\",\r\n\"url\":\"mail.google.com\"\r\n}]")]
        public string SupportedHosts {
            get {
                return ((string)(this["SupportedHosts"]));
            }
            set {
                this["SupportedHosts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MaxConnectionPerHost {
            get {
                return ((int)(this["MaxConnectionPerHost"]));
            }
            set {
                this["MaxConnectionPerHost"] = value;
            }
        }
    }
}
